# Simple workflow for deploying /docs content to GitHub Pages

name: Deploy /docs content to Pages

on:
  push:
    branches: ["main"]  # 触发条件：当推送至main分支时
  workflow_dispatch:  # 也可以手动触发工作流

permissions:
  contents: read  # 需要读取仓库内容的权限
  pages: write   # 需要写入Pages的权限

concurrency:
  group: "pages"
  cancel-in-progress: true  # 如果有正在进行的部署，则取消它并开始新的部署

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # 部署后页面的URL

    runs-on: ubuntu-latest  # 使用Ubuntu最新版本的环境运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码到工作目录

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用一个广泛使用的action来部署到GitHub Pages
        with:
          # 使用docs目录作为发布的源
          publish_dir: ./docs
          # （可选）如果您的站点需要Jekyll处理，默认是false
          # jekyll: false
          # GitHub Pages环境变量，对于个人或组织页通常是GITHUB_TOKEN
          github_token: ${{ secrets.WORKFLOW }}
          # （可选）是否强制添加CNAME文件到根目录，默认为false
          # cname: your-custom-domain.com
