# Simple workflow for deploying static content from /docs to GitHub Pages
name: Deploy /docs content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Assuming you want the site to be published at https://<username>.github.io/<repo>
          # If your repository is under a user or organization page (e.g., https://<username>.github.io), 
          # then you might not need this step or you may set `publish_dir: docs`
          publish_dir: docs
      - name: Prepare Docs
        run: mv docs/* ./
        # This step moves all files from the docs folder to the root, assuming you want the site root to reflect the docs content.
        # Adjust if your structure should be different.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Now pointing to the root where the docs content has been moved
          path: './'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
